config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, path: 'admin', controllers: {
    sessions: 'admin/admins/sessions'
  }

  namespace :admin do
    root 'users#index'
    resources :posts, only: [:index, :destroy]
    resources :users, only: [:index, :show, :destroy]
  end

  scope module: :public do
    devise_for :users
    root to: "homes#top"
    get 'homes/about' => 'homes#about'
    get 'search',  to: 'searches#search'

    resources :posts do
      resource :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    resources :users, only: [:index, :show, :edit, :update]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_many :relationships, foreign_key: :follower_id, class_name:"Relationship", dependent: :destroy
  # has_many :followings, through: :relationships, source: :followed
  # has_many :reverse_of_relationships, foreign_key: :followed_id, class_name: "Relationship", dependent: :destroy
  # has_many :followers, through: :reverse_of_relationships, source: :follower

  # has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  # has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy

  has_one_attached :profile_image

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  def get_profile_image(width, height)
    if profile_image.attached?
    profile_image.variant(resize_to_limit: [width, height]).processed
    else
      'no_image.jpg'
    end
  end

  def self.search_for(keyword, method)
    case method
    when "exact"
      User.where(name: keyword)
    when "prefix"
      User.where('name LIKE ?', "#{keyword}%")
    when "suffix"
      User.where('name LIKE ?', "%#{keyword}")
    when "partial"
      User.where('name LIKE ?', "%#{keyword}%")
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash.now[:notice] = "ユーザー情報を更新しました。"
      redirect_to user_path(@user)
    else
      flash.now[:alert] = "ユーザー情報の更新に失敗しました。"
      render :edit, status: :unprocessable_entity
    end
  end

  def is_matching_login_user
    user = User.find(params[:id])

    unless user.id == current_user.id
      redirect_to posts_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render 'layouts/error_messages', resource: @user %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>プロフィール編集</h2>
      <%= form_with model: @user, url: user_path(@user), local: true, html: { enctype: "multipart/form-data" } do |f| %>
      
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control', placeholder:"名前"%>
        </div>

        <div class="form-group">
          <%= f.label :profile_image %>
          <%= f.file_field :profile_image, accept: "image/*", class: 'form-control-file' %>
        </div>

        <div class="form-group">
          <%= f.label :introduction %>
          <%= f.text_area :introduction, class: 'form-control', placeholder:"自己紹介" %>
        </div>

        <div class="form-group">
          <%= f.submit "変更を保存", class: 'btn btn-secondary' %>
        </div>
      <% end %>

    </div>
  </div>

</div>

app/views/users/show.html.erb
<div class="container py-5">
  <div class="row">

    <div class="col-lg-4 mb-4">
      <div class="card shadow-sm p-4 sticky-top" style="top: 20px;">
        <h3 class="h4 text-center mb-3">プロフィール</h3>
        <div class="text-center mb-3">
          <%= image_tag @user.get_profile_image(100, 100), class: "rounded-circle border mb-2" %>
          <h4><%= @user.name %></h4>
        </div>

        <p class="text-muted"><%= @user.introduction %></p>

        <% if @user == current_user  %>
        <hr>
        <%= link_to 'プロフィール編集', edit_user_path(@user), class: 'btn btn-outline-info btn-block' %>
        <% end %>
      </div>
    </div>

    <div class="col-lg-8">
      <h3 class="mb-4"><%= @user.name %> さんの推し活記録 (<%= @posts.count %>件)</h3>

      <% if @posts.empty? %>
        <p class="text-muted">まだ推し活記録の投稿がありません。</p>
      <% else %>

        <div class="row">
          <% @posts.each do |post| %>
            <div class="col-md-6 mb-4">
              <div class="card shadow-lg h-100">
                <%= link_to post_path(post) do %>
                  <%= image_tag post.get_image(300, 200), class: "card-img-top" %>
                <% end %>

                <div class="card-body">
                  <h5 class="card-title">
                    <%= link_to post.title, post_path(post), class: "text-dark" %>
                  </h5>
                  <small class="text-muted">
                  <%= post.created_at.strftime("%Y/%m/%d") %> |
                  <i class="fas fa-comment"></i> <%= post.comments.count %>
                  </small>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>