config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, path: 'admin', controllers: {
    sessions: 'admin/admins/sessions'
  }

  namespace :admin do
    root 'users#index'
    resources :posts, only: [:index, :destroy]
    resources :users, only: [:index, :show, :destroy]
  end

  scope module: :public do
    devise_for :users
    root to: "homes#top"
    get 'homes/about' => 'homes#about'
    get 'search',  to: 'searches#search'

    resources :posts do
      resource :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    resources :users, only: [:index, :show, :edit, :update]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200 }
  has_one_attached :image

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def self.search_for(keyword, method)
    case method
    when "exact"
      Post.where(title: keyword)
    when "prefix"
      Post.where('title LIKE ?', "#{keyword}%")
    when "suffix"
      Post.where('title LIKE ?', "%#{keyword}")
    when "partial"
      Post.where('title LIKE ?', "%#{keyword}%")
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def index
    @posts = Post.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_users_path(@users), notice: "投稿（ID: #{@post.id}）を削除しました。"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = "投稿に成功しました"
      redirect_to post_path(@post)
    else
      flash.now[:alert] = "投稿に失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
       flash[:notice] = "投稿を更新しました。"
       redirect_to post_path(@post)
    else
      flash.now[:alert] = "投稿を更新できませんでした。"
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "投稿を削除しました。"
    redirect_to posts_path
  end

  private

  def post_params
  params.require(:post).permit(:title, :body, :image, :address, :latitude, :longitude, :source_url)
  end

  def is_matching_login_user
    @post = Post.find(params[:id])
    unless @post.user == current_user
      redirect_to posts_path, alert: "この投稿を編集する権限はありません。"
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-md-8 col-md-6 mx-auto">
    <%= render 'layouts/error_messages', resource: post %>
    <%= form_with model: post, local: true, html: {enctype: "multipart/form-data"} do |f| %>
  
      <div class="form-group text-center">
        <%= f.label :image do %>
          <p class="mb-2">現在の画像</p>
          <%= image_tag post.get_image(300, 200), class: "img-fluid mb-2 border rounded shadow-sm" %>
            <span class="btn btn-outline-secondary btn-block">画像を選択/変更</span>
          <% end %>
        <%= f.file_field :image, accept: 'image/*', class: 'd-none' %>
      </div>

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: 'タイトルを入力' %>
      </div>

      <div class="form-group">
        <%= f.label :address, "場所(住所)" %>
        <%= f.text_field :address, class: 'form-control', placeholder: '例：東京都千代田区千代田〇〇' %>
      </div>

      <div class="form-group">
        <%= f.label :body, "詳細・エピソード" %>
        <%= f.text_area :body, rows: 5, class: 'form-control', placeholder: '推しの詳細、具体的なエピソード' %>
      </div>

      <%= f.hidden_field :latitude %>
      <%= f.hidden_field :longitude %>

      <div class="form-group mt-4">
        <% button_text = post.new_record? ? "新規投稿する" : "変更を保存する" %>
        <%= f.submit button_text, class: 'btn btn-success btn-lg btn-block' %>
      </div>

    <% end %>

  </div>
</div>

app/views/posts/_list.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post_path(post) %></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<div class="container py-5">
  <h2 class="text-center mb-5">「<%= @post.title %>」の編集</h2>
  <%= render 'form', post: @post %>

  <div class="text-center mt-4">
    <%= link_to "削除する", post_path(@post), method: :delete, data: { confirm: '本当にこの投稿を削除しますか？' }, class: 'text-danger' %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container py-5">
  <h2 class="text-center mb-4">投稿一覧</h2>
  
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-md-4 mb-4">
        <div class="card shadow-lg h-100">
          <%= link_to post_path(post) do %>
            <%= image_tag post.get_image(300, 200), class: "card-img-top" %>
          <% end %>
          <div class="card-body d-flex flex-column">
            <h5>
              <%= link_to post.title, post_path(post), class: "text-dark" %>
            </h5>

            <div class="d-flex align-items-center mt-2">
              <div class="mr2">
                <%= image_tag post.user.get_profile_image(50, 50), class: "rounded-circle" %>
              </div>
              <div>
                <small class="text-muted">By
                  <%= link_to post.user.name, user_path(post.user), class: "text-info" %>
                </small>
              </div>
            </div>

            <div class="mt-2">
              <i class="fas fa-comment"></i><%= post.comments.count %> コメント
            </div>

            <small class="text-muted mt-auto pt-2">
              <%= post.created_at.strftime("%Y/%m/%d %H:%M") %>
            </small>

          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/posts/new.html.erb
<%= render 'layouts/error_messages', resource: @post %>

<div class="container">
  <div class="row no-gutters">
    <div class="col-md-6 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h3 class="text-center bg-dark text-light p-4">新規投稿</h3>

      <%= form_with model: @post, local: true, html: { enctype: "multipart/form-data" } do |f| %>
        <div class="form-body p-4">

          <div class="form-group">
            <%= f.label :image, "写真を選択" %>
            <%= f.file_field :image, accept: "image/*", class: "form-control-file" %>
          </div>

          <div class="form-group">
            <%= f.label :title, "タイトル" %>
            <%= f.text_field :title, class: "form-control" %>
          </div>
          
          <div class="form-group">
            <%= f.label :body, "詳細・エピソード" %>
            <%= f.text_area :body, rows: 5, class: 'form-control', placeholder: '推しの詳細、具体的なエピソード' %>
          </div>

          <div class="form-group">
            <%= f.label :address, "住所" %>
            <%= f.text_field :address, class: "form-control", placeholder: "例: 東京都庁" %>
          </div>

          <div class="text-center">
            <%= f.submit "投稿", class: "btn btn-primary mt-3" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <div class="card shadow-lg mb-5 border-0">
        <%= image_tag @post.get_image(800, 500), class: "card-img-top rounded-t-lg" %>
        <div class="card-body p-5">
          <h1 class="card-title mb-4 font-weight-bold"><%= @post.title %></h1>
          <div class="d-flex align-items-center mb-4 border-bottoom pb-3">
            <%= link_to user_path(@post.user) do %>
              <%= image_tag @post.user.get_profile_image(50, 50), class: "rounded-circle mr-3" %>
            <% end %>
            
            <div>
              <small class="text-muted">投稿者：</small>
              <h5 class="mb-0"><%= @post.user.name %></h5>
              <small class="text-muted"><%= @post.created_at.strftime("%Y/%m/%d %H:%M") %></small>
            </div>

            <h6 class="text-secondary mb-3">
            <i class="fas fa-map-marker-alt mr-2"></i>場所：<%= @post.address %>
            </h6>

            <div class="mt-4 post-body">
              <%= safe_join(@post.body.split("\n"), tag(:br)) %>
            </div>

            <% if @post.user == current_user %>
              <div class="mt-5 text-right">
                <%= link_to "編集", edit_post_path(@post), class: 'btn btn-outline-info mr-3' %>
                <%= link_to "削除", post_path(@post), method: :delete, data: {confirm: '本当に削除しますか？'}, class: 'btn btn-outline-danger' %>
              </div>
            <% end %>


          </div>
        </div>
      </div>

      <div class="comment-area mt-5">
        <h3 class="mb-3"><i class="far fa-comments"></i>コメント (<%= @post.comments.count %>)</h3>
        <%= render 'comments/form', post: @post, comment: @comment %>
      </div>
      
    </div>
  </div>
</div>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>