config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, path: 'admin', controllers: {
    sessions: 'admin/admins/sessions'
  }

  namespace :admin do
    root 'users#index'
    resources :posts, only: [:index, :destroy]
    resources :users, only: [:index, :show, :destroy]
  end

  scope module: :public do
    devise_for :users
    root to: "homes#top"
    get 'homes/about' => 'homes#about'
    get 'search',  to: 'searches#search'

    resources :posts do
      resource :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

    resources :users, only: [:index, :show, :edit, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  devise authentication_keys: [:email]
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/oshi.rb
class Oshi < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200 }
  has_one_attached :image

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def self.search_for(keyword, method)
    case method
    when "exact"
      Post.where(title: keyword)
    when "prefix"
      Post.where('title LIKE ?', "#{keyword}%")
    when "suffix"
      Post.where('title LIKE ?', "%#{keyword}")
    when "partial"
      Post.where('title LIKE ?', "%#{keyword}%")
    end
  end
end

app/models/post_oshi.rb
class PostOshi < ApplicationRecord
  belongs_to :post
  belongs_to :oshi
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_many :relationships, foreign_key: :follower_id, class_name:"Relationship", dependent: :destroy
  # has_many :followings, through: :relationships, source: :followed
  # has_many :reverse_of_relationships, foreign_key: :followed_id, class_name: "Relationship", dependent: :destroy
  # has_many :followers, through: :reverse_of_relationships, source: :follower

  # has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  # has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy

  has_one_attached :profile_image

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  def get_profile_image(width, height)
    if profile_image.attached?
    profile_image.variant(resize_to_limit: [width, height]).processed
    else
      'no_image.jpg'
    end
  end

  def self.search_for(keyword, method)
    case method
    when "exact"
      User.where(name: keyword)
    when "prefix"
      User.where('name LIKE ?', "#{keyword}%")
    when "suffix"
      User.where('name LIKE ?', "%#{keyword}")
    when "partial"
      User.where('name LIKE ?', "%#{keyword}%")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    posts_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected
  def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :introduction])
  devise_parameter_sanitizer.permit(:account_update, keys: [:name, :introduction, :profile_image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    post = Post.find(params[:post_id])
    comment = current_user.comments.new(comment_params)
    comment.post_id = post.id
    
    if comment.save
      flash[:notice] = "コメントを投稿しました。"
    else
      flash[:alert] = "コメントの投稿に失敗しました。"
    end
    redirect_to post_path(post)
  end

  def destroy
    post = Post.find(params[:post_id])
    comment = post.comments.find(params[:id])
    comment.destroy
    flash[:notice] = "コメントを削除しました。"
  end

  private
  def comment_params
  params.require(:comment).permit(:content)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  layout "top"

  def top
    render layout: "top"
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = "投稿に成功しました"
      redirect_to post_path(@post)
    else
      flash.now[:alert] = "投稿に失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
       flash[:notice] = "投稿を更新しました。"
       redirect_to post_path(@post)
    else
      flash.now[:alert] = "投稿を更新できませんでした。"
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "投稿を削除しました。"
    redirect_to posts_path
  end

  private

  def post_params
  params.require(:post).permit(:title, :body, :image, :address, :latitude, :longitude, :source_url)
  end

  def is_matching_login_user
    @post = Post.find(params[:id])
    unless @post.user == current_user
      redirect_to posts_path, alert: "この投稿を編集する権限はありません。"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash.now[:notice] = "ユーザー情報を更新しました。"
      redirect_to user_path(@user)
    else
      flash.now[:alert] = "ユーザー情報の更新に失敗しました。"
      render :edit, status: :unprocessable_entity
    end
  end

  def is_matching_login_user
    user = User.find(params[:id])

    unless user.id == current_user.id
      redirect_to posts_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/_admin_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container">
    <%= link_to "Oshi Map Console", admin_root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li class="nav-item">
            <%= link_to "Users", admin_users_path, class: 'nav-link text-dark' %>
          </li>
          <li class="nav-item">
            <%= link_to "Posts", admin_posts_path, class: 'nav-link text-dark' %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container">
    <%= link_to "Oshi Map", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if false #user_signed_in? %>
          <li class="nav-item mr-3 d-flex align-items-center">
            <%= search_form_for @q, url: posts_path, class: "form-inline" do |f| %>
              <div class="input-group">
                <%= f.search_field :title_or_body_cont,
                                  class: "form-control form-control-sm",
                                  placeholder: "タイトルや本文を検索" %>
                <div class="input-group-append">
                  <button type="submit" class="btn btn-outline-light btn-sm">
                    <i class="fas fa-search"></i>
                  </button>
                </div>
              </div>
            <% end %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "HOME", root_path, class: 'nav-link text-light' %>
        </li>
        <li class="nav-item">
          <%= link_to "About", homes_about_path, class: 'nav-link text-light' %>
        </li>
        <% if user_signed_in? %>

          <li class="nav-item mr-3">
            <%= link_to new_post_path, class: "btn btn-outline-light" do %>
              <i class="fas fa-plus"></i>新規投稿
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "Posts", posts_path, class: 'nav-link text-light' %>
          </li>
          <li class="nav-item">
            <%= link_to "My Page", user_path(current_user), class: 'nav-link text-light' %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link text-light' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: 'nav-link text-light' %>
          </li>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: 'nav-link text-light' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Console | Oshimap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/42bec750f8.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="mb-5">
      <%= render "layouts/admin_navigation" %>
    </header>
    <div class="container">
      <%#= "flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oshimap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/42bec750f8.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="mb-5">
      <%= render "layouts/navigation" %>
      <%= render "public/searches/form" %>
    </header>
    <div class="container">
      <%#= "flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oshimap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/42bec750f8.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>